[display]
image_path = ""
default_image_path = ""
background_color = "black"
monitor_index = 1

[dynamic_marquee]
enabled = false
itgmania_display_enabled = false
itgmania_display_file_path = ""
itgmania_base_path = ""
itgmania_banner_path = ""

