[display]
image_path = "C:/Repositories/arcade_station/assets/images/banners/ddr-v.png" 
default_image_path = "C:/Repositories/arcade_station/assets/images/banners/supernova.png" 
background_color = "transparent" 
monitor_index = 1 
dynamic_marquee_enabled = true 