[display]
image_path = "C:/Repositories/arcade_station/assets/images/banners/ddr-v.png"
default_image_path = "C:/Repositories/arcade_station/assets/images/banners/supernova.png"
background_color = "black"
monitor_index = 1

[dynamic_marquee]
enabled = true
itgmania_display_enabled = true
itgmania_display_file_path = "C:/Games/ITGmania/Themes/Simply Love/Modules/ArcadeStationMarquee.log"
itgmania_base_path = "C:/Games/ITGmania"
itgmania_banner_path = "C:/Games/ITGmania/Themes/Simply Love/Modules/simply-love.png"
