[display]
image_path = ""
default_image_path = ""
background_color = "black"
monitor_index = 1

[dynamic_marquee]
enabled = false
itgmania_display_enabled = true
itgmania_display_file_path = "C:/Users/dean/AppData/Roaming/ITGmania/Themes/Simply Love/Modules/ArcadeStationMarquee.log"
itgmania_base_path = ""
itgmania_banner_path = "C:/Users/dean/AppData/Roaming/ITGmania/Themes/Simply Love/Modules/itgmania.png"

