[games]
itgmania = "C:/Games/ITGmania/Program/ITGmania.exe"
not_itg = "C:/path/to/NotITG.exe"
stepmania_3.9 = ""
itg_3 = ""
itg_2 = ""
itg_1 = ""
mungyodance_3 = ""
ddr_starlight = ""
ddr_omnimix = ""
ddr_a3 = ""
ddr_a20 = ""
ddr_extreme_proclarity = ""
ddr_extreme = ""
ddr_max2 = ""
ddr_max = ""
ddr_5thmix = ""
ddr_4thmix = ""
ddr_3rdmix = ""
ddr_2ndmix = ""
ddr_1st_mix = ""
ds_disneys_rave = ""
ds_true_kiss_destination = ""
ds_dreams_come_true = ""
ds_euromix_2 = ""
ds_euromix = ""
ds_1 = ""