[key_mappings]
"ctrl+~" = "../arcade_station/core/windows/restart_computer.ps1"
"ctrl+f2" = "../arcade_station/core/windows/restore_windows_shell.ps1"
"ctrl+f3" = "../arcade_station/core/windows/setup_windows_shell.ps1"
"ctrl+f4" = "../arcade_station/core/common/start_streaming.py" 
"ctrl+f5" = "C:/Users/me/AppData/Local/Programs/cursor/Cursor.exe" 
"ctrl+f6" = "C:/Windows/explorer.exe"
"ctrl+f7" = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe" 
"ctrl+space" = "../arcade_station/core/common/kill_all_and_reset_pegasus.py"
"+" = "../../bin/windows/take_screenshot.vbs"
"/" = "../../bin/windows/take_screenshot.vbs"