[key_mappings]
"ctrl+`" = "../arcade_station/core/windows/restart_computer.ps1"
"ctrl+f2" = "../arcade_station/core/windows/restore_pc_mode.ps1"
"ctrl+f3" = "../arcade_station/core/windows/setup_kiosk_mode.ps1"
"ctrl+f4" = "../arcade_station/core/common/start_streaming.py" 
"ctrl+f6" = "C:/Windows/explorer.exe"
"ctrl+space" = "../arcade_station/core/common/kill_all_and_reset_pegasus.py"
"ctrl+f9" = "../arcade_station/core/common/kill_all.py"
"ctrl+f10" = "../kill_arcade_station.bat"
"+" = "../arcade_station/screenshot.py"
"/" = "../arcade_station/screenshot.py"