[processes]
names = [
    "cmd",
    "explorer",
    "gslauncher",
    "In The Groove",
    "ITGmania",
    "i_view64",
    "LightsTest",
    "mame",
    "mame2lit",
    "mame_lights",
    "mmc",
    "notepad",
    "notepad++",
    "NotITG-v4.2.0",
    "OpenITG",
    "OpenITG-PC",
    "outfox",
    "pegasus-fe_windows",
    "regedit",
    "spice",
    "spice64",
    "StepMania",
    "Taskmgr",
    "timeout",
    "marquee_image"
] 