[screenshot]
monitor_index = 0 
file_location = "" 
file_name = "" 
quality = "High" 
sound_file = "../../../../assets/sounds/megatouch_yahoo.wav" 

[icloud_upload]
enabled = true
interval_seconds = 360
delete_after_upload = true
upload_directory = ""
apple_services_path = "C:/Program Files (x86)/Common Files/Apple/Internet Services/"
processes_to_restart = ["iCloudServices","iCloudPhotos"] 