[screenshot]
monitor_index = 0 
file_location = "C:/Users/me/Pictures/Uploads" 
file_name = "" 
quality = "High" 
sound_file = "../../../../assets/sounds/megatouch_yahoo.wav" 

[icloud_upload]
enabled = false
interval_seconds = 300
delete_after_upload = true
upload_directory = "C:/Users/me/Pictures/Uploads"
apple_services_path = "C:/Program Files (x86)/Common Files/Apple/Internet Services/"
processes_to_restart = [
  "iCloudServices",
  "iCloudPhotos"
] 