[lights]
light_reset_executable_path = "C:/Repositories/arcade_station/bin/windows/LightsTest.exe"
light_mame_executable_path = "C:/Repositories/arcade_station/bin/windows/mame2lit.exe"
enabled = false

[streaming]
obs_executable = "C:/Program Files/obs-studio/bin/64bit/obs64.exe"
obs_arguments = "--startstreaming --disable-shutdown-check"
webcam_management_executable = "C:/Program Files/Logitech/LogiCapture/bin/LogiCapture.exe"
webcam_management_enabled = true 

[vpn]
enabled = false
vpn_application_directory = "C:/Program Files/OpenVPN/bin" 
vpn_application = "openvpn-gui.exe" 
vpn_process = "openvpn" 
vpn_config_profile = "gradius-DRDOOFUS-phaseii-config.ovpn" 
seconds_to_wait = 10 

[osd]
enabled = true
sound_osd_executable = "C:/Program Files (x86)/AudioSwitch/AudioSwitch.exe"