[lights]
enabled = true
light_reset_executable_path = "C:/Repositories/arcade_station/bin/windows/LightsTest.exe"
light_mame_executable_path = "C:/Repositories/arcade_station/bin/windows/mame2lit.exe"

[streaming]
webcam_management_enabled = true 
webcam_management_executable = "C:/Program Files/Logitech/LogiCapture/bin/LogiCapture.exe"
obs_executable = "C:/Program Files/obs-studio/bin/64bit/obs64.exe"
obs_arguments = "--startstreaming --disable-shutdown-check"

[vpn]
enabled = true
vpn_application_directory = "C:/Program Files/OpenVPN/bin" 
vpn_application = "openvpn-gui.exe" 
vpn_process = "openvpn" 
vpn_config_profile = "gradius-DRDOOFUS-phaseii-config.ovpn" 
seconds_to_wait = 10 

[osd]
enabled = true
sound_osd_executable = "C:/Program Files (x86)/AudioSwitch/AudioSwitch.exe"